# Generated by Django 5.1.5 on 2025-06-30 16:16

import cloudinary.models
import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opinion', models.TextField()),
                ('rating', models.IntegerField()),
                ('sug', models.TextField()),
            ],
            options={
                'verbose_name': 'Website Reviews',
                'verbose_name_plural': 'Website Reviews',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', colorfield.fields.ColorField(blank=True, choices=[('', '---------'), ('#007BFFFF', 'Blue'), ('#1D097FFF', 'Blue2'), ('#28A745FF', 'Green'), ('#DC3545FF', 'Red'), ('#895188FF', 'Cyan'), ('#6C757DFF', 'Gray'), ('#CBC3FFFF', 'Gray2'), ('#651A89FF', 'Dark'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#CF1DBDFF', 'Violet'), ('#9027E9FF', 'Violet2')], default=None, help_text='Main brand color used throughout the site', image_field=None, max_length=25, null=True, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(blank=True, choices=[('', '---------'), ('#007BFFFF', 'Blue'), ('#1D097FFF', 'Blue2'), ('#28A745FF', 'Green'), ('#DC3545FF', 'Red'), ('#895188FF', 'Cyan'), ('#6C757DFF', 'Gray'), ('#CBC3FFFF', 'Gray2'), ('#651A89FF', 'Dark'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#CF1DBDFF', 'Violet'), ('#9027E9FF', 'Violet2')], default=None, help_text='Secondary color for accents and highlights', image_field=None, max_length=25, null=True, samples=None)),
                ('buttons_color', colorfield.fields.ColorField(blank=True, choices=[('', '---------'), ('#007BFFFF', 'Blue'), ('#1D097FFF', 'Blue2'), ('#28A745FF', 'Green'), ('#DC3545FF', 'Red'), ('#895188FF', 'Cyan'), ('#6C757DFF', 'Gray'), ('#CBC3FFFF', 'Gray2'), ('#651A89FF', 'Dark'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#CF1DBDFF', 'Violet'), ('#9027E9FF', 'Violet2')], default=None, help_text='Color for all action buttons', image_field=None, max_length=25, null=True, samples=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Configuración actualmente activa')),
                ('bathroom_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Bathroom 1')),
                ('bathroom_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Bathroom 2')),
                ('bathroom_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Bathroom 3')),
                ('bathroom_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Bathroom 4')),
                ('bathroom_5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Bathroom 5')),
                ('bathroom_6', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Bathroom 6')),
                ('bathroom_7', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Bathroom 7')),
                ('bathroom_8', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Bathroom 8')),
                ('bathroom_9', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Bathroom 9')),
                ('bathroom_10', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Bathroom 10')),
                ('kitchen_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kitchen 1')),
                ('kitchen_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kitchen 2')),
                ('kitchen_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kitchen 3')),
                ('kitchen_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kitchen 4')),
                ('kitchen_5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kitchen 5')),
                ('kitchen_6', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kitchen 6')),
                ('kitchen_7', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kitchen 7')),
                ('kitchen_8', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kitchen 8')),
                ('kitchen_9', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kitchen 9')),
                ('kitchen_10', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kitchen 10')),
                ('fireplace_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fireplace 1')),
                ('fireplace_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fireplace 2')),
                ('fireplace_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fireplace 3')),
                ('fireplace_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fireplace 4')),
                ('fireplace_5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fireplace 5')),
                ('fireplace_6', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fireplace 6')),
                ('fireplace_7', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fireplace 7')),
                ('fireplace_8', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fireplace 8')),
                ('fireplace_9', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fireplace 9')),
                ('fireplace_10', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Fireplace 10')),
                ('image_carrousel_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Carousel 1')),
                ('image_carrousel_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Carousel 2')),
                ('image_carrousel_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Carousel 3')),
                ('granite_countertop_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Granite 1')),
                ('granite_countertop_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Granite 2')),
                ('quartz_countertop_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Quartz 1')),
                ('quartz_countertop_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Quartz 2')),
                ('quartzite_countertop_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Quartzite 1')),
                ('quartzite_countertop_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Quartzite 2')),
                ('image_before', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Before')),
                ('image_after', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='After')),
                ('admin_perfil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Admin Profile')),
                ('admin_2_perfil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Admin 2 Profile')),
                ('architect', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Architect Profile')),
                ('company_picture_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Company 1')),
                ('company_picture_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Company 2')),
                ('company_picture_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Company 3')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendar',
                'ordering': ['date', 'time_slot'],
                'unique_together': {('date', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Describe your needs')),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.schedule')),
            ],
            options={
                'verbose_name': 'List of orders',
                'verbose_name_plural': 'List of orders',
                'ordering': ['date'],
            },
        ),
    ]
