# Generated by Django 5.1.5 on 2025-07-02 04:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='admin_2_perfil',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='admin_perfil',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='architect',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='company_picture_1',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='company_picture_2',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='company_picture_3',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='granite_countertop_1',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='granite_countertop_2',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='quartz_countertop_1',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='quartz_countertop_2',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='quartzite_countertop_1',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='quartzite_countertop_2',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='image_carrousel_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Second slider 4'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='image_carrousel_5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Second slider 5'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='image_carrousel_6',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Second slider 6'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='image_granite',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Granite'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='image_marble',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Marble'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='image_quartz',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Quartz'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='image_quartzite',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Quartzite'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='image_carrousel_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Main slider 1'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='image_carrousel_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Main slider 2'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='image_carrousel_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Main slider 3'),
        ),
    ]
