# Generated by Django 5.1.5 on 2025-07-29 17:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_siteconfiguration_buttons_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='primary_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Main brand color used in buttons', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Color used of background of the website', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
