# Generated by Django 5.1.5 on 2025-05-28 23:21

import colorfield.fields
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date'], 'verbose_name': 'List of orders', 'verbose_name_plural': 'List of orders'},
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='company_picture_4',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='company_picture_5',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='image_scrolleable_1',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='image_scrolleable_2',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='image_scrolleable_3',
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='admin_2_perfil',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='admin_perfil',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='architect',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bathroom_1',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bathroom_10',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bathroom_2',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bathroom_3',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bathroom_4',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bathroom_5',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bathroom_6',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bathroom_7',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bathroom_8',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bathroom_9',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='buttons_color',
            field=colorfield.fields.ColorField(blank=True, choices=[('', '---------'), ('#007BFFFF', 'Blue'), ('#1D097FFF', 'Blue2'), ('#28A745FF', 'Green'), ('#DC3545FF', 'Red'), ('#895188FF', 'Cyan'), ('#6C757DFF', 'Gray'), ('#CBC3FFFF', 'Gray2'), ('#651A89FF', 'Dark'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#CF1DBDFF', 'Violet'), ('#9027E9FF', 'Violet2')], default=None, help_text='Color for all action buttons', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='company_picture_1',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='company_picture_2',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='company_picture_3',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='fireplace_1',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='fireplace_10',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='fireplace_2',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='fireplace_3',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='fireplace_4',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='fireplace_5',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='fireplace_6',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='fireplace_7',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='fireplace_8',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='fireplace_9',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='granite_countertop_1',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='granite_countertop_2',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='image_after',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='image_before',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='image_carrousel_1',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='image_carrousel_2',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='image_carrousel_3',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='kitchen_1',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='kitchen_10',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='kitchen_2',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='kitchen_3',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='kitchen_4',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='kitchen_5',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='kitchen_6',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='kitchen_7',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='kitchen_8',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='kitchen_9',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='primary_color',
            field=colorfield.fields.ColorField(blank=True, choices=[('', '---------'), ('#007BFFFF', 'Blue'), ('#1D097FFF', 'Blue2'), ('#28A745FF', 'Green'), ('#DC3545FF', 'Red'), ('#895188FF', 'Cyan'), ('#6C757DFF', 'Gray'), ('#CBC3FFFF', 'Gray2'), ('#651A89FF', 'Dark'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#CF1DBDFF', 'Violet'), ('#9027E9FF', 'Violet2')], default=None, help_text='Main brand color used throughout the site', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='quartz_countertop_1',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='quartz_countertop_2',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='quartzite_countertop_1',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='quartzite_countertop_2',
            field=models.ImageField(blank=True, null=True, storage=orders.models.StaticStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=colorfield.fields.ColorField(blank=True, choices=[('', '---------'), ('#007BFFFF', 'Blue'), ('#1D097FFF', 'Blue2'), ('#28A745FF', 'Green'), ('#DC3545FF', 'Red'), ('#895188FF', 'Cyan'), ('#6C757DFF', 'Gray'), ('#CBC3FFFF', 'Gray2'), ('#651A89FF', 'Dark'), ('#FFFFFFFF', 'White'), ('#000000FF', 'Black'), ('#CF1DBDFF', 'Violet'), ('#9027E9FF', 'Violet2')], default=None, help_text='Secondary color for accents and highlights', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
