# Generated by Django 5.1.5 on 2025-06-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
