# Generated by Django 5.1.5 on 2025-06-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_delete_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="admin_2_perfil",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="admin_perfil",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="architect",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="bathroom_1",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="bathroom_10",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="bathroom_2",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="bathroom_3",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="bathroom_4",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="bathroom_5",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="bathroom_6",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="bathroom_7",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="bathroom_8",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="bathroom_9",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="company_picture_1",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="company_picture_2",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="company_picture_3",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="fireplace_1",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="fireplace_10",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="fireplace_2",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="fireplace_3",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="fireplace_4",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="fireplace_5",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="fireplace_6",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="fireplace_7",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="fireplace_8",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="fireplace_9",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="granite_countertop_1",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="granite_countertop_2",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="image_after",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="image_before",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="image_carrousel_1",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="image_carrousel_2",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="image_carrousel_3",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="kitchen_1",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="kitchen_10",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="kitchen_2",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="kitchen_3",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="kitchen_4",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="kitchen_5",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="kitchen_6",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="kitchen_7",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="kitchen_8",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="kitchen_9",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="quartz_countertop_1",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="quartz_countertop_2",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="quartzite_countertop_1",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="quartzite_countertop_2",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="admin_2_perfil_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="admin_2_perfil_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="admin_perfil_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="admin_perfil_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="architect_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="architect_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_10_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_10_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_1_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_1_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_2_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_2_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_3_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_3_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_4_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_4_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_5_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_5_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_6_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_6_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_7_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_7_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_8_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_8_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_9_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bathroom_9_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="company_picture_1_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="company_picture_1_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="company_picture_2_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="company_picture_2_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="company_picture_3_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="company_picture_3_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_10_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_10_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_1_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_1_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_2_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_2_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_3_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_3_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_4_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_4_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_5_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_5_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_6_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_6_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_7_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_7_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_8_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_8_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_9_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="fireplace_9_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="granite_countertop_1_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="granite_countertop_1_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="granite_countertop_2_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="granite_countertop_2_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="image_after_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="image_after_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="image_before_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="image_before_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="image_carrousel_1_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="image_carrousel_1_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="image_carrousel_2_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="image_carrousel_2_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="image_carrousel_3_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="image_carrousel_3_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_10_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_10_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_1_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_1_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_2_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_2_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_3_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_3_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_4_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_4_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_5_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_5_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_6_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_6_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_7_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_7_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_8_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_8_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_9_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="kitchen_9_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="quartz_countertop_1_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="quartz_countertop_1_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="quartz_countertop_2_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="quartz_countertop_2_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="quartzite_countertop_1_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="quartzite_countertop_1_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="quartzite_countertop_2_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="quartzite_countertop_2_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
