# Generated by Django 5.1.5 on 2025-06-13 16:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_remove_siteconfiguration_admin_2_perfil_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="buttons_color",
            field=colorfield.fields.ColorField(
                blank=True,
                choices=[("", "---------"), ("#FF5733", "Red"), ("#33FF57", "Green")],
                default=None,
                help_text="Color for all action buttons",
                image_field=None,
                max_length=18,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="primary_color",
            field=colorfield.fields.ColorField(
                blank=True,
                choices=[("", "---------"), ("#FF5733", "Red"), ("#33FF57", "Green")],
                default=None,
                help_text="Main brand color used throughout the site",
                image_field=None,
                max_length=18,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="secondary_color",
            field=colorfield.fields.ColorField(
                blank=True,
                choices=[("", "---------"), ("#FF5733", "Red"), ("#33FF57", "Green")],
                default=None,
                help_text="Secondary color for accents and highlights",
                image_field=None,
                max_length=18,
                null=True,
                samples=None,
            ),
        ),
    ]
